# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='mainapp/uploads/')),
                ('commentaire', models.TextField(max_length=500)),
                ('tag1', models.CharField(blank=True, max_length=10)),
                ('tag2', models.CharField(blank=True, max_length=10)),
                ('tag3', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coordonnee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('nomrue', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('hidden_address', 'Peut cacher son adresse aux exterieurs a la famille'), ('hidden_telephone', 'Peut cacher son telephone aux exterieurs a la famille')),
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='famille/default.png', upload_to='famille/')),
            ],
        ),
        migrations.CreateModel(
            name='Historien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=50)),
                ('validation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom2', models.CharField(blank=True, max_length=30)),
                ('prenom3', models.CharField(blank=True, max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('date_nais', models.CharField(max_length=10)),
                ('date_dece', models.DateField(blank=True, null=True, verbose_name='date deces')),
                ('date_mariage', models.CharField(blank=True, max_length=10, null=True)),
                ('nationalite', models.CharField(max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(default='profil/default.png', upload_to='profil/')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Famille')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('admin_famille', 'Peut administrer une famille'), ('confirmation', "Peut confirmer l'acces a une famille")),
            },
        ),
        migrations.CreateModel(
            name='Lien_Parente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Famille')),
                ('individu1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individu1', to='mainapp.Individu')),
                ('individu2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individu2', to='mainapp.Individu')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Lien_Parente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='lien_parente',
            name='nom_lien_parente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Nom_Lien_Parente'),
        ),
        migrations.AddField(
            model_name='banque',
            name='individu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Individu'),
        ),
    ]
