# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20161212_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='mainapp.Individu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='mainapp.Individu'),
        ),
    ]
