# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
