# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20161216_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banque',
            options={'permissions': (('validation', "Attente de validation de la part d'un historien"),)},
        ),
    ]
