# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20161219_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='banque',
            name='comHistorien',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='banque',
            name='dateHistorien',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='banque',
            name='fichier',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
