# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20161223_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banque',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='banque',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='banque',
            name='tag3',
        ),
        migrations.AddField(
            model_name='banque',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
